# docker-compose.yml
version: "3.9"

services:

  ollama:
    image: ollama/ollama:latest
    container_name: oolasystems_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ollama-init:
    image: ollama/ollama:latest
    container_name: oolasystems_ollama_init
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: >
      /bin/sh -c "
      until ollama list > /dev/null 2>&1;
      do sleep 2;
      done;
      ollama pull qwen2.5:7b;
      "

    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
